# Site settings
title: OpenTheia
email: craigaloewen@gmail.com
description: >
  OpenTheia - Making Touchscreens Accessible

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://OpenTheia.github.io # the base hostname & protocol for your site
git_address: https://github.com/OpenTheia/OpenTheia.github.io
git_edit_address: https://github.com/OpenTheia/OpenTheia.github.io

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
